import asyncpg

from database.models import GameModel

class DataBaseManager:
    def __init__(self, pool):
        self.__pool: asyncpg.Pool = pool 

    @classmethod
    async def create(cls, user, password):
        pool = await asyncpg.create_pool(user=user, password=password)
        return cls(pool)
    
    @property
    async def init_db(self):
        await self.__pool.execute("CREATE TABLE games (game_id INT PRIMARY KEY, NAME VARCHAR(255), DATE TIMESTAMP)")
        await self.__pool.execute("CREATE TABLE price_history (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, game_id INT, PRICE FLOAT, DATE TIMESTAMP)")

    async def close(self):
        self.__pool.close()

    async def add_game(self, game: GameModel):
        await self.__pool.execute("INSERT INTO games (game_id, name, date) VALUES ($1, $2, $3)", game.game_id, game.name, game.date)
        await self.__pool.execute("INSERT INTO price_history (game_id, price, date) VALUES ($1, $2, $3)", game.game_id, game.price, game.date)

    async def remove_game(self, game_id):
        return await self.__pool.execute("DELETE FROM games WHERE game_id=$1", game_id)

    async def update(self, game: GameModel):
        await self.__pool.execute("UPDATE games SET date = $1 WHERE game_id = $2",  game.date, game.game_id)
        await self.__pool.execute("INSERT INTO price_history (game_id, price, date) VALUES ($1, $2, $3)", game.game_id, game.price, game.date)

    async def select(self, game: GameModel):
        result_raw = await self.__pool.fetch("SELECT price, date FROM price_history WHERE game_id=$1 ORDER BY date DESC LIMIT 6", game.game_id)
        result = [dict(i) for i in result_raw]

        data = {"price": [], "date": []}
        
        for item in result:
            data["price"].append(item["price"])
            data["date"].append(item["date"])

        return data

